name: Clinical Data Analysis Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute DataFrame Analysis Notebook
      run: |
        jupyter nbconvert --execute --to html Punith_Basaralu_Sugegowda_df.ipynb

    - name: Execute RDD Analysis Notebook
      run: |
        jupyter nbconvert --execute --to html Punith_Basaralu_Sugegowda_rdd.ipynb

    - name: Execute SQL Script
      run: |
        spark-submit Punith_Basaralu_Sugegowda_sql.sql
